# Generated by Django 5.2.6 on 2025-10-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('soft', 'Soft Reservation'), ('firm', 'Firm Reservation'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('booked', 'Booked')], default='soft', max_length=50),
        ),
    ]
