# Generated by Django 5.2.6 on 2025-10-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "make",
                    models.CharField(
                        choices=[
                            ("toyota", "Toyota"),
                            ("honda", "Honda"),
                            ("ford", "Ford"),
                            ("bmw", "BMW"),
                            ("mercedes", "Mercedes"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        choices=[
                            ("corolla", "Corolla"),
                            ("civic", "Civic"),
                            ("mustang", "Mustang"),
                            ("x5", "X5"),
                            ("c-class", "C-Class"),
                        ],
                        max_length=50,
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                (
                    "car_type",
                    models.CharField(
                        choices=[
                            ("suv", "SUV"),
                            ("sedan", "Sedan"),
                            ("hatchback", "Hatchback"),
                            ("coupe", "Coupe"),
                            ("convertible", "Convertible"),
                        ],
                        max_length=50,
                    ),
                ),
                ("color", models.CharField(max_length=30)),
                ("seats", models.PositiveIntegerField()),
                (
                    "transmission",
                    models.CharField(
                        choices=[("automatic", "Automatic"), ("manual", "Manual")],
                        max_length=20,
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("petrol", "Petrol"),
                            ("diesel", "Diesel"),
                            ("electric", "Electric"),
                            ("hybrid", "Hybrid"),
                        ],
                        max_length=20,
                    ),
                ),
                ("has_ac", models.BooleanField(default=True)),
                ("has_gps", models.BooleanField(default=False)),
                ("hourly_rate", models.DecimalField(decimal_places=2, max_digits=8)),
                ("deposit_amount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("is_available", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "availability_status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("rented", "Rented"),
                            ("maintenance", "Maintenance"),
                            ("unavailable", "Unavailable"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
