# Generated by Django 5.2.6 on 2025-10-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_inventories", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="car_type",
            field=models.CharField(
                choices=[
                    ("suv", "SUV"),
                    ("sedan", "Sedan"),
                    ("hatchback", "Hatchback"),
                    ("coupe", "Coupe"),
                    ("convertible", "Convertible"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="color",
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="car",
            name="fuel_type",
            field=models.CharField(
                choices=[
                    ("petrol", "Petrol"),
                    ("diesel", "Diesel"),
                    ("electric", "Electric"),
                    ("hybrid", "Hybrid"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="has_ac",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="has_gps",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="car",
            name="make",
            field=models.CharField(
                choices=[
                    ("toyota", "Toyota"),
                    ("honda", "Honda"),
                    ("ford", "Ford"),
                    ("bmw", "BMW"),
                    ("mercedes", "Mercedes"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="model",
            field=models.CharField(
                choices=[
                    ("corolla", "Corolla"),
                    ("civic", "Civic"),
                    ("mustang", "Mustang"),
                    ("x5", "X5"),
                    ("c-class", "C-Class"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="seats",
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="transmission",
            field=models.CharField(
                choices=[("automatic", "Automatic"), ("manual", "Manual")],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="year",
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
