# Generated by Django 5.2.6 on 2025-10-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_inventories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='images',
            field=models.TextField(blank=True, null=True),
        ),
    ]
