# Generated by Django 5.2.6 on 2025-10-20 14:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_inventories', '0002_car_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='images',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='images'),
            preserve_default=False,
        ),
    ]
