# Generated by Django 5.2.6 on 2025-10-02 23:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_inventories", "0002_alter_car_car_type_alter_car_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="year",
            field=models.PositiveIntegerField(
                db_index=True,
                validators=[
                    django.core.validators.MinValueValidator(2000),
                    django.core.validators.MaxValueValidator(2026),
                ],
            ),
        ),
    ]
