# Generated by Django 5.2.6 on 2025-10-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='deposit_amount',
            field=models.PositiveIntegerField(default=0, help_text='Deposit amount in cents'),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.PositiveIntegerField(default=0, help_text='Total price in cents'),
        ),
    ]
