# Generated by Django 5.2.6 on 2025-10-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_business_owner',
            field=models.BooleanField(default=False),
        ),
    ]
